name: Continuous Integration - stable version

on:
  push:
    branches: [ 12.0 ]

jobs:

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: ghcr.io/thindil/build:10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Debug build
      run: |
        git config --global --add safe.directory /__w/steamsky/steamsky
        nimble debug -y

    - name: Run the tests
      run: others/tests.nims 30

    - name: Check with Nimalyzer
      run: /root/.nimble/bin/nimalyzer others/nimalyzer.cfg

    - name: Upload the log
      uses: actions/upload-artifact@v4
      if: failure()
      with:
         name: nimalyzer.log
         path: nimalyzer.log

  build_linux:

    if: ${{ always() }}
    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/build:10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build the program
      run: |
        git config --global --add safe.directory /__w/steamsky/steamsky
        others/build.nims x86_64-linux-gnu

    - name: Compress the artifact
      run: tar -cf steamsky-development-linux.tar -C release steamsky-linux

    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
         name: steamsky-development-linux.tar
         path: steamsky-development-linux.tar

  build_windows:

    if: ${{ always() }}
    needs: tests

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/buildwin64:10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build the program
      run: |
        git config --global --add safe.directory /__w/steamsky/steamsky
        apt-get update
        apt-get install -y gcc
        others/build.nims x86_64-windows

    - name: Compress the artifact
      run: tar -cf steamsky-development-windows.tar -C release steamsky-windows

    - name: Upload the artifact
      uses: actions/upload-artifact@v4
      with:
         name: steamsky-development-windows.tar
         path: steamsky-development-windows.tar
