name: Gnatprove checks

on:
  push:
    branches: [ master ]

jobs:

  tests:

    runs-on: ubuntu-latest

    container: ghcr.io/thindil/adabuild:10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Spark
      run: |
         mkdir obj
         nohup gnatprove --checks-as-errors -P steamsky.gpr > spark.log

    - name: Upload the log
      uses: actions/upload-artifact@v2
      with:
         name: logs
         path: |
            spark.log
            obj/gnatprove/gnatprove.out

